site_name: Wito Documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_submodules: true
            docstring_style: google
            docstring_section_style: spacy
            heading_level: 3
            show_if_no_docstring: false
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Reference:
    - Interface: reference/wito/interface.md
    - Configuration:
      - Settings: reference/configuration/settings.md